#!/usr/bin/env bash
set -euo pipefail
[ -e libs/recyclerview-1.3.2.jar ] || { echo "libs/ not vendored — run ./vendor-libs.sh first" >&2; exit 1; }
[ -e libs/api-13.1.5.jar ] || { echo "libs/ missing Shizuku — re-run ./vendor-libs.sh" >&2; exit 1; }
export ANDROID_HOME="${ANDROID_HOME:-/Users/tarikbc/Library/Android/sdk}"
BT="$ANDROID_HOME/build-tools/35.0.0"
PLATDIR="$ANDROID_HOME/platforms/android-34"; PLAT="$PLATDIR/android.jar"
PKG=com.tarikbc.emubackup; OUT=build; rm -rf "$OUT"; mkdir -p "$OUT/gen" "$OUT/obj" "$OUT/apk"

# 1. compile + link resources -> R.java + compiled resources
# Compile the whole res/ dir in one call so a bad resource (e.g. an illegal
# '--' inside an XML comment) FAILS THE BUILD LOUDLY instead of being
# silently dropped.
"$BT/aapt2" compile --dir src/main/res -o "$OUT/obj/res.zip"

# RecyclerView needs androidx.recyclerview.R to exist and be loadable at
# runtime — its precompiled bytecode reads it unconditionally on every
# construction. This build never merges AARs, so vendor-libs.sh keeps the
# res/ + AndroidManifest.xml of every AAR whose classes reference their own
# R in libs/aar/<name>/; we compile those alongside our own res and use
# --extra-packages so aapt2 emits real R.java per package against one merged
# table. The four Shizuku AARs carry no resources, so they never land here.
EXTRA_PKGS=""
AAR_RES_ARGS=()
if [ -d libs/aar ]; then
  for aar in libs/aar/*/; do
    name="$(basename "$aar")"
    [ -d "${aar}res" ] || continue
    "$BT/aapt2" compile --dir "${aar}res" -o "$OUT/obj/aar_${name}.zip"
    AAR_RES_ARGS+=("$OUT/obj/aar_${name}.zip")
    pkg="$(grep -o 'package="[^"]*"' "${aar}AndroidManifest.xml" | head -1 | sed 's/package="//;s/"$//')"
    [ -n "$pkg" ] && EXTRA_PKGS="${EXTRA_PKGS:+$EXTRA_PKGS:}$pkg"
  done
fi

# -A src/main/assets ships targets.json (the emulator path registry) and the
# seed game-name database. Without it the app has no registry and scans nothing.
"$BT/aapt2" link -o "$OUT/apk/base.ap_" -I "$PLAT" \
  --manifest src/main/AndroidManifest.xml --java "$OUT/gen" \
  -A src/main/assets \
  --min-sdk-version 26 --target-sdk-version 34 \
  --version-code "${VERSION_CODE:-1}" --version-name "${VERSION_NAME:-dev}" \
  ${EXTRA_PKGS:+--extra-packages "$EXTRA_PKGS"} \
  $(ls "$OUT/obj"/*.flat 2>/dev/null) $([ -f "$OUT/obj/res.zip" ] && echo "$OUT/obj/res.zip") \
  "${AAR_RES_ARGS[@]}"

# 2. AIDL -> java. The privileged file interface that Shizuku loads into a
# shell-UID process (see docs/ARCHITECTURE.md). Generated sources land in
# $OUT/gen, which step 3 already sweeps, so no extra compile plumbing.
if [ -d src/main/aidl ]; then
  while IFS= read -r f; do
    # Only interface definitions produce code. A bare `parcelable Foo;` file is a
    # forward declaration for the -I include path; handing it to aidl emits a
    # zero-byte Foo.java that then shadows the real hand-written Parcelable in
    # the srcs list. Skip those.
    grep -qE '^[[:space:]]*(oneway[[:space:]]+)?interface[[:space:]]' "$f" || continue
    "$BT/aidl" -p"$PLATDIR/framework.aidl" -Isrc/main/aidl -o"$OUT/gen" "$f"
  done < <(find src/main/aidl -name '*.aidl')
fi

# 3. Google OAuth client id, injected at build time rather than committed.
# Unset is a supported configuration: the app then reports Drive as "not
# configured in this build" and uses a local folder instead. CI relies on this.
mkdir -p "$OUT/gen/com/tarikbc/emubackup"
cat > "$OUT/gen/com/tarikbc/emubackup/OAuthConfig.java" <<JAVA
package com.tarikbc.emubackup;
/** Generated by build.sh from the environment. Do not edit or commit. */
public final class OAuthConfig {
    public static final String CLIENT_ID     = "${EMUBACKUP_DRIVE_CLIENT_ID:-}";
    public static final String CLIENT_SECRET = "${EMUBACKUP_DRIVE_CLIENT_SECRET:-}";
    public static boolean isConfigured() { return !CLIENT_ID.isEmpty(); }
    private OAuthConfig() {}
}
JAVA

# 4. compile java (app sources + generated R/AIDL/OAuthConfig + libs)
CP="$PLAT"; for j in libs/*.jar; do [ -e "$j" ] && CP="$CP:$j"; done
find src/main/java "$OUT/gen" -name '*.java' > "$OUT/srcs.txt"
javac --release 17 -cp "$CP" -d "$OUT/classes" @"$OUT/srcs.txt"

# 5. dex
"$BT/d8" --min-api 26 --output "$OUT" $(find "$OUT/classes" -name '*.class') $(ls libs/*.jar 2>/dev/null || true)

# 6. package dex into the ap_, align, sign
cd "$OUT/apk" && cp base.ap_ emubackup.unsigned.apk && cd - >/dev/null
( cd "$OUT" && zip -uj apk/emubackup.unsigned.apk classes.dex >/dev/null )
"$BT/zipalign" -f 4 "$OUT/apk/emubackup.unsigned.apk" "$OUT/emubackup.apk"

# Signing. Defaults to a local throwaway DEBUG key (auto-generated on first run
# since keystore/ is git-ignored). CI overrides these env vars with a real
# RELEASE key from GitHub Secrets on tag builds, so published releases are
# stably signed (updates install over each other).
KEYSTORE="${KEYSTORE:-keystore/emubackup-debug.jks}"
# Exported so apksigner can read them from the environment (env: spec below)
# instead of the process argv, where `ps` would expose a real release password.
export STOREPASS="${STOREPASS:-emubackup123}"
export KEYPASS="${KEYPASS:-emubackup123}"
KEYALIAS="${KEYALIAS:-emubackup}"
if [ "$KEYSTORE" = "keystore/emubackup-debug.jks" ] && [ ! -f "$KEYSTORE" ]; then
  mkdir -p keystore
  keytool -genkeypair -keystore "$KEYSTORE" -storepass "$STOREPASS" \
    -keypass "$KEYPASS" -alias "$KEYALIAS" -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=EmuBackup Debug, O=EmuBackup" >/dev/null 2>&1
fi
"$BT/apksigner" sign --ks "$KEYSTORE" --ks-pass "env:STOREPASS" \
  --key-pass "env:KEYPASS" --ks-key-alias "$KEYALIAS" "$OUT/emubackup.apk"
echo "built $OUT/emubackup.apk"
